services:
  backend:
    build: ./backend
    container_name: f1_kpi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - cache:/backend/cache
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: f1_kpi_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  cache:
